// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhBbdZwCza55YobS15-qoNoAtxDuc1gxg',
    appId: '1:996962506706:web:61561d1e13b19d52bd5a0b',
    messagingSenderId: '996962506706',
    projectId: 'fir-auth-e5ffd',
    authDomain: 'fir-auth-e5ffd.firebaseapp.com',
    storageBucket: 'fir-auth-e5ffd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmv605nYFzGBJ2tkTF_iFZmczdeXnlP2s',
    appId: '1:996962506706:android:8c5828fe5fb2322fbd5a0b',
    messagingSenderId: '996962506706',
    projectId: 'fir-auth-e5ffd',
    storageBucket: 'fir-auth-e5ffd.appspot.com',
  );
}
